accounts/urls.py
from django.urls import include, path

from accounts import views

app_name = "accounts"

urlpatterns = [
	path("login/", views.LoginView.as_view(), name="login"),
	path("logout/", views.LogoutView.as_view(), name="logout"),
	path("create/", views.CreateAccountView.as_view(), name="create"),
	path("update/", views.UpdateAccountView.as_view(), name="update"),
	path("change_password/", views.UpdatePasswordView.as_view(), name="change_password"),
	path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),
	path("password_reset/", views.ResetPasswordView.as_view(), name="password_reset"),
	path(
		"password_reset/<uidb64>/<token>/",
		views.ResetPasswordConfirmView.as_view(),
		name="password_reset_confirm"
	),
]

admin_pages/urls.py
from django.urls import path, include

from admin_pages import views

urlpatterns = [
	path('', views.AdminView.as_view(), name="index"),
	path('export/activities/', views.ExportActivities.as_view(), name="activities.csv"),
	path('export/slots/', views.ExportSlots.as_view(), name="slots.csv"),
	path('export/participants/', views.ExportParticipants.as_view(), name="participants.csv"),
	path('export/activity_choices/', views.ExportActivityChoices.as_view(), name="activity_choices.csv"),
	path('email/send_user_emails_0564946523/', views.SendUserEmail.as_view(), name="email_users"),
	path('email/send_orga_emails_5682480453/', views.SendOrgaEmail.as_view(), name="email_orgas"),
	path('email/new_email/', views.NewEmail.as_view(), name="email_new"),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import RedirectView
from django.urls import path, include

from home import views

sitemaps = {"static_pages": views.StaticViewSitemap}

urlpatterns = [
	path('', views.HomeView.as_view(), name = 'home'),
	path('inscription/', views.RegisterView.as_view(), name = 'inscription'),
	path('desinscription/', views.UnregisterView.as_view(), name="desinscription"),
	path('activites/', views.ActivityView.as_view(), name = 'activites'),
	path('activites/nouvelle/', views.ActivitySubmissionView.as_view(), name = 'activity_submission'),
	path('faq/', views.FAQView.as_view(), name = 'FAQ'),
	path("profil/", views.ProfileView.as_view(), name="profile"),
	path('favicon.ico', RedirectView.as_view(url='/static/imgs/favicon.ico')),
	path(
		'sitemap.xml', sitemap, {'sitemaps': sitemaps},
		name='django.contrib.sitemaps.views.sitemap'
	),
	path('admin_pages/', include(('admin_pages.urls', 'admin_pages'), namespace="admin_pages")),
	path('comptes/', include("accounts.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interludes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
        path('admin/', admin.site.urls),
        path('', include('home.urls')),
    ]

home/forms.py
from django import forms
from django.core.exceptions import ValidationError

from home import models
from shared.forms import FormRenderMixin


class InscriptionForm(FormRenderMixin, forms.ModelForm):

	class Meta:
		model = models.ParticipantModel
		fields = (
			"school", "sleeps", # "mug",
			"meal_friday_evening", "meal_saturday_morning", "meal_saturday_midday",
			"meal_saturday_evening", "meal_sunday_morning", "meal_sunday_midday", "meal_sunday_evening",
			"paid","nb_murder", "comment"
		)

	field_groups = [["school"], ["sleeps"], #["mug"],
		[
			"meal_friday_evening", "meal_saturday_morning", "meal_saturday_midday",
			"meal_saturday_evening", "meal_sunday_morning", "meal_sunday_midday", "meal_sunday_evening"
		],
		["paid"],["nb_murder"], ["comment"]
	]

	def save(self, *args, commit=True, **kwargs):
		participant = super().save(*args, commit=False, **kwargs)
		participant.is_registered = True
		if commit:
			participant.save()
		return participant

class ActivityForm(FormRenderMixin, forms.ModelForm):
	class Meta:
		model = models.ActivityChoicesModel
		fields = ("slot",)
		labels = {"slot":""}

	def __init__(self, *args, **kwargs):
		super(ActivityForm, self).__init__(*args, **kwargs)
		slots = models.SlotModel.objects.filter(subscribing_open=True)
		self.fields['slot'].queryset = slots

class BaseActivityFormSet(forms.BaseFormSet):
	"""Form set that fails if duplicate activities"""
	def clean(self):
		"""Checks for duplicate activities"""
		if any(self.errors):
			# Don't bother validating the formset unless each form is valid on its own
			return
		activities = []
		for form in self.forms:
			if self.can_delete and self._should_delete_form(form):
				continue
			activity = form.cleaned_data.get('slot')
			if activity is None:
				continue
			if activity in activities:
				raise ValidationError("Vous ne pouvez pas sélectionner une même activtté plusieurs fois")
			activities.append(activity)


class ActivitySubmissionForm(FormRenderMixin, forms.ModelForm):

	class Meta:
		model = models.ActivityModel
		fields = (
			"title", "act_type", "game_type", "description",

			"host_name", "host_email", "host_info",

			"must_subscribe", "communicate_participants",
			"max_participants",	"min_participants",

			"duration", "desired_slot_nb",
			"available_friday_evening",
			"available_friday_night",
			"available_saturday_morning",
			"available_saturday_afternoon",
			"available_saturday_evening",
			"available_saturday_night",
			"available_sunday_morning",
			"available_sunday_afternoon",
			"constraints",

			#"status",
			"needs",

			"comments",
		)

	def clean(self):
		cleaned_data = super().clean()
		maxi = cleaned_data.get("max_participants")
		mini = cleaned_data.get("min_participants")
		if maxi != 0 and mini > maxi:
			raise forms.ValidationError(
				"Le nombre minimal de participants est supérieur au nombre maximal",
				code="invalid_order"
			)
		return cleaned_data

	def save(self, *args, commit=True, **kwargs):
		"""Enregistre l'activité dans la base de données"""
		activity = models.ActivityModel(
			**self.cleaned_data,
		)
		if commit:
			activity.save()
		return activity

home/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sitemaps import Sitemap
from django.forms import formset_factory
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, RedirectView, TemplateView, View

from home import models
from home.forms import ActivityForm, ActivitySubmissionForm, BaseActivityFormSet, InscriptionForm
from site_settings.models import SiteSettings


# ==============================
# Site static pages
# ==============================


class HomeView(TemplateView):
	"""Vue pour la page d'acceuil"""
	template_name = "home.html"

def get_planning_context():
	"""Returns the context dict needed to display the planning"""
	settings = SiteSettings.load()
	context = dict()
	context['planning'] = models.SlotModel.objects.filter(on_planning=True).order_by("title")
	if settings.date_start is not None:
		context['friday'] = settings.date_start.day
		context['saturday'] = (settings.date_start + timedelta(days=1)).day
		context['sunday'] = (settings.date_start + timedelta(days=2)).day
	else:
		context['friday'] = 1
		context['saturday'] = 2
		context['sunday'] = 3
	return context

class ActivityView(TemplateView):
	"""Vue pour la liste des activités"""
	template_name = "activites.html"

	def get_context_data(self, **kwargs):
		"""ajoute la liste des activités au contexte"""
		context = super(ActivityView, self).get_context_data(**kwargs)
		context['activities'] = models.ActivityModel.objects.filter(display=True).order_by("title")
		context.update(get_planning_context())
		return context


class FAQView(TemplateView):
	"""Vue pour la FAQ"""
	template_name = "faq.html"


# ==============================
# Profile and registration
# ==============================


class ProfileView(LoginRequiredMixin, TemplateView):
	"""Vue des actions de gestion de son profil"""
	template_name = "profile.html"
	redirect_field_name = "next"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		settings = SiteSettings.load()
		if settings.activities_allocated:
			my_choices = models.ActivityChoicesModel.objects.filter(
				participant=self.request.user.profile,
				accepted=True
			)
		else:
			my_choices = models.ActivityChoicesModel.objects.filter(
				participant=self.request.user.profile
			)

		context["my_choices"] = my_choices
		return context


class RegisterClosed(TemplateView):
	"""Vue pour quand les inscriptions ne sont pas ouvertes"""
	template_name = "inscription/closed.html"

class RegisterSignIn(TemplateView):
	"""Vue affichée quand les inscriptions sont ouverte mais
	l'utilisateur n'est pas connecté"""
	template_name = "inscription/signin.html"

class RegisterUpdateView(LoginRequiredMixin, TemplateView):
	"""Vue pour s'inscrire et modifier son inscription"""
	template_name = "inscription/form.html"
	form_class = InscriptionForm
	formset_class = formset_factory(form=ActivityForm, extra=3, formset=BaseActivityFormSet)
	success_url = reverse_lazy("profile")

	@staticmethod
	def get_slots(participant):
		activities = models.ActivityChoicesModel.objects.filter(participant=participant).order_by("priority")
		return [{"slot": act.slot} for act in activities]

	@staticmethod
	def set_activities(participant, formset):
		# delete old activites
		models.ActivityChoicesModel.objects.filter(participant=participant).delete()

		priority = 0
		for form in formset:
			data = form.cleaned_data
			if data:
				slot = data["slot"]
				models.ActivityChoicesModel(
					priority=priority, participant=participant, slot=slot
				).save()
				priority += 1

	def get(self, request, *args, **kwargs):
		participant = request.user.profile
		slots = self.get_slots(participant)
		form = self.form_class(instance=participant)
		formset = self.formset_class(initial=slots)
		context = {"form": form, "formset": formset}
		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		settings = SiteSettings.load()
		form = self.form_class(request.POST, instance=request.user.profile)
		if settings.activity_inscriptions_open : # meal + sleep + activities open
			formset = self.formset_class(request.POST)
			if not (form.is_valid() and formset.is_valid()):
				context = {"form": form, "formset": formset}
				return render(request, self.template_name, context)
			self.set_activities(request.user.profile, formset)

		else: # only meal and sleep open
			if not form.is_valid():
				participant = request.user.profile
				slots = self.get_slots(participant)
				formset = self.formset_class(initial=slots)
				context = {"form": form, "formset": formset}
				return render(request, self.template_name, context)
		
		form.save()

		messages.success(request, "Votre inscription a bien été enregistrée")
		return redirect(self.success_url, permanent=False)

class RegisterView(View):
	"""Vue pour l'inscription
	repartie sur les vue RegisterClosed, RegisterSignIn et RegisterUpdateView"""
	def dispatch(self, request, *args, **kwargs):
		settings = SiteSettings.load()
		if not settings.inscriptions_open:
			return RegisterClosed.as_view()(request)
		if not request.user.is_authenticated:
			return RegisterSignIn.as_view()(request)
		return RegisterUpdateView.as_view()(request)


class UnregisterView(LoginRequiredMixin, RedirectView):
	pattern_name = "profile"

	def get_redirect_url(self, *args, **kwargs):
		participant = self.request.user.profile
		participant.is_registered = False
		participant.save()
		messages.success(self.request, "Vous avez été désinscrit")
		return reverse(self.pattern_name)


# ==============================
# Activity Submission Form
# ==============================


class ActivitySubmissionView(LoginRequiredMixin, FormView):
	"""Vue pour proposer une activité"""
	template_name = "activity_submission.html"
	form_class = ActivitySubmissionForm
	success_url = reverse_lazy("profile")

	@staticmethod
	def submission_check():
		"""Vérifie si le formulaire est ouvert ou non"""
		settings = SiteSettings.load()
		return settings.activity_submission_open

	def get_initial(self):
		init = super().get_initial()
		user = self.request.user
		init.update({
			"host_name": "{} {}".format(user.first_name, user.last_name),
			"host_email": user.email,
		})
		return init

	def not_open(self, request):
		"""Appelé quand le formulaire est désactivé"""
		messages.error(request, "La soumission d'activité est desactivée")
		return redirect(self.success_url, permanent=False)

	def get(self, request, *args, **kwargs):
		if not self.submission_check():
			return self.not_open(request)
		return super().get(self, request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		if not self.submission_check():
			return self.not_open(request)
		form = self.form_class(request.POST)
		if not form.is_valid():
			context = self.get_context_data()
			context["form"] = form
			return render(request, self.template_name, context)

		form.save()

		messages.success(request, "Votre activité a bien été enregistrée. Elle sera affichée sur le site après relecture par les admins.")
		return redirect(self.success_url, permanent=False)


# ==============================
# Sitemap
# ==============================


class StaticViewSitemap(Sitemap):
	"""Vue générant la sitemap.xml du site"""
	changefreq = 'monthly'

	def items(self):
		"""list of pages to appear in sitemap"""
		return ["home", "inscription", "activites", "FAQ"]

	def location(self, item):
		"""real url of an item"""
		return reverse(item)

	def priority(self, obj):
		"""priority to appear in sitemap"""
		# Priorize home page over the rest in search results
		if obj == "home" or obj == "":
				return 0.8
		else:
			return None # defaults to 0.5 when unset

home/templates/activites.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<script src="{% static 'js/vis-timeline.min.js' %}"></script>
{% endblock %}

{% block nav_activite %}current{% endblock %}

{% block "content" %}

	{% if settings.activity_submission_open %}
	<ul class="messagelist">
		<li class="info">
			Vous pouver proposer une activité en remplissant <a href="{% url 'activity_submission' %}">ce formulaire</a>.
		</li>
	</ul>{% endif %}

	{% if settings.display_planning %}
		<h2>Planning</h2>
		{% include "_planning.html" %}
	{% endif %}

	<h2>Activités</h2>
	<p>Durant tout l'événement, des jeux seront en libre-service et des tables disponibles pour jouer.
		Certaines activités ne pourront se faire qu'avec inscription au vue d'une préparation en amont ou d'un nombre de places limité.
	</p>
	{% if settings.activity_submission_form %}
	<p>Vous pouver proposer une activité en remplissant <a href="{{ settings.activity_submission_form }}">ce formulaire</a>.</p>
	{% endif %}

	{% if activities %}
	<p id="act-list"><strong>Liste des activités&nbsp;:</strong></p>
	<ul>
		{% for activity in activities %}
		<li><a href="#{{ activity.slug }}">{{ activity.title }}</a></li>
		{% endfor %}
	</ul>
	{% endif %}

	{% for activity in activities %}
		<h3 id="{{ activity.slug }}">{{ activity.title }}</h3>

		<dl>
			<dt>Durée :</dt><dd>{{ activity.pretty_duration }}</dd>
			{% if activity.host_name %}
			<dt>Orga :</dt><dd>{{ activity.host_name }}</dd>
			{% endif %}
			{% if settings.show_host_emails and activity.show_email %}
			<dt>Contact :</dt><dd><a href="mailto:{{ activity.host_email }}">{{ activity.host_email }}</a></dd>
			{% endif %}
			<dt>Type :</dt><dd>{{ activity.pretty_type }}</dd>
			<dt>Places :</dt><dd>{{ activity.nb_participants }}</dd>
			{% if activity.slots and settings.display_planning %}
			<dt>Heure/Lieu :</dt><dd>{% for slot in activity.slots %}
				{{ slot.start|date:"l H:i" }}{% if slot.room %} {{ slot.room }}{% endif %}{% if not forloop.last %},<br> {% endif %}
				{% endfor %}
			</dd>
			{% endif %}
			<dt>Description :</dt>
		</dl>
		<div class="desc">
		{% if activity.desc_as_html %}
			{{ activity.description|safe }}
		{% else %}
		<p class="indent">{{ activity.description|linebreaksbr }}</p>
		{% endif %}
		</div>
		<a style="text-decoration: none;" href="#act-list"><i class="fa fa-arrow-up"></i> Retour à la liste</a>
	{% empty %}

	<p>Il n'y a aucune activité pour l'instant, revenez dans quelques jours pour avoir une liste plus remplie.</p>

	{% endfor %}
{% endblock %}

home/templates/base.html
{% spaceless %}
{% load static %}
<!doctype html>
<html lang="fr">

<head>
	<!-- WEBSITE VERSION {{ constants.WEBSITE_FULL_VERSION }} -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>{% block title %}Interludes{% if settings.date_start %} {{ settings.date_start.year }}{% endif %}{% endblock %}</title>
		<meta name="description" content="Inscriptions et infos sur les interENS ludiques{% if settings.date_start %}, édition {{ settings.date_start.year }}{% endif %}">
		<meta name="keywords" content="Interludes ENS {% if settings.date_start %}{{ settings.date_start.year }} {% endif %}InterENS">
		<link rel="icon" type="image/png" href="{% static 'imgs/2023/favicon.ico' %}">

		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?v={{ constants.CSS_VERSION }}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome-all.min.css' %}">
		{% block head %}{% endblock %}
	</head>

	<body>
		<header>
			<div id="header_logo"  class="easter_egg">
				<h1><a href="/"><img src="{% static 'imgs/2023/logo.png' %}">&nbsp;Interludes{% if settings.date_start %} {{ settings.date_start.year }}{% endif %}&nbsp;</a></h1>
			</div>
			<div id="head_main_infos">
			<div id="location">{{ settings.hosting_school }}</div>
			<div id="date">{% if settings.date_start %}
				{% if settings.date_end %}
				{{ settings.date_start.day }}-{{ settings.date_end }}
				{% else %}
				{{ settings.date_start }}
				{% endif %}
				{% else %}
				Date non-fixée
				{% endif %}</div>
			</div>
		</header>

		<script type="text/javascript">
			function toggle_menu() {
				var nav = document.getElementById("nav");
				if (nav.className === "") {
					nav.className += "responsive";
				} else {
					nav.className = "";
				}
			}
		</script>

		<nav id="nav">
			<a href="{% url 'home' %}" rel="text/html"
				class="{% block nav_home %}{% endblock %}">
				Accueil
			</a>
			<a href="{% url 'inscription' %}" rel="text/html"
				class="{% block nav_inscription %}{% endblock %}">
				Inscriptions
			</a>
			<a href="{% url 'activites' %}" rel="text/html"
				class="{% block nav_activite %}{% endblock %}">
				Activités
			</a>
			<a href="{% url 'FAQ' %}" rel="text/html"
				class="{% block nav_faq %}{% endblock %}">
				FAQ
			</a>
			{% if request.user.is_authenticated %}
				<a href="{% url 'profile' %}"
					class="{% block nav_profile %}{% endblock %}">
					Mon compte
				</a>
			{% else %}
				<a href="{% url 'accounts:login' %}"
					class="{% block nav_login %}{% endblock %}">
					Connexion
				</a>
			{% endif %}
			{% if user.is_superuser %}
			<a href="{% url 'admin_pages:index' %}"
				class="{% block nav_admin %}{% endblock %}">
				Administration
			</a>
			{% endif %}
			<a href="javascript:void(0);" class="icon" onclick="toggle_menu()">
				<i class="fa fa-bars"></i>
			</a>
		</nav>

		<main>
			{% if messages %}
			<ul class="messagelist">
				{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% if settings.global_message %}
				{% if settings.global_message_as_html %}
					{{ settings.global_message|safe }}
				{% else %}
					<ul class="messagelist"><li class="info">{{ settings.global_message }}</li></ul>
				{% endif %}
			{% endif %}

			{% block "content" %}
			{% endblock %}
		</main>

	<footer>
		<div id="sponsors">
			<a class="external" href="https://www.ens-paris-saclay.fr/">
				<img src="{% static "imgs/2023/ens_ps.png" %}" alt="École Normale Supérieure Paris-Saclay"
					title="École Normale Supérieure Paris-Saclay" />
			</a>
			<a class="external" href="https://wiki.crans.org/VieBdl">
    			<img src="{% static "imgs/2023/bdl.png" %}" alt="Bureau des Loisirs de l'ENS de Paris-Saclay"
    				title="Bureau des Loisirs de l'ENS Paris-Saclay" />
			</a>
		</div>
		{% if settings.contact_email %}
		<p>Pour tout problème, contacter&nbsp;:<br><span class="antispam">{{ settings.contact_email_reversed }}</span>
		</p>
		{% endif %}
	</footer>

	</body>

</html>
{% endspaceless %}

home/templates/profile.html
{% extends "base.html" %}

{% block nav_profile %}current{% endblock %}

{% block "content" %}

<h2>Mon compte</h2>

<p>Connecté en tant que {{ user.first_name }} {{ user.last_name }} ({{ user.email }})</p>

{% if user.is_superuser %}
<ul class="messagelist">
<li class="info">
	Vous avez les droits d'administrateurs.
	<br>Aller à la <a href="{% url 'admin_pages:index' %}">page d'administration du site</a>
	{% if user.is_staff %}
	<br>Aller à la <a href="{% url 'admin:index' %}">page d'administration de django</a>
	(N'y modifier rien sy vous n'êtes pas sûrs de vous)
	{% endif %}
</li>
</ul>{% endif %}

{% if user.profile.is_registered %}
	<strong>Mon inscription&nbsp;:</strong>
	{% if settings.inscriptions_open and settings.inscriptions_end %}
	  modifiable jusqu'au {{ settings.inscriptions_end|date:"l d F Y à H:i" }}
	{% endif %}
	<ul>
		<li>Tarif personnalisé : {{ user.profile.cost }}€</li>
		<li>{% if user.profile.sleeps %}Inscrit pour dormir sur place{% else %}Non inscrit pour dormir sur place{% endif %}</li>
		{% comment "pas de tasse" %}<li>{% if user.profile.mug %}Commandse une tasse{% else %}Ne commande pas de tasse{% endif %}</li>{% endcomment%}
		{% if user.profile.nb_meals != 0 %}
		<li>Inscrit à {{ user.profile.nb_meals }} repas :</li>
			<ul>
				{% if user.profile.meal_friday_evening == True %}<li>Vendredi soir</li>{% endif %}
				{% if user.profile.meal_saturday_morning == True %}<li>Petit dej' du samedi</li>{% endif %}
				{% if user.profile.meal_saturday_midday == True %}<li>Samedi midi</li>{% endif %}
				{% if user.profile.meal_saturday_evening == True %}<li>Samedi soir</li>{% endif %}
				{% if user.profile.meal_sunday_morning == True %}<li>Petit dej' du dimanche</li>{% endif %}
				{% if user.profile.meal_sunday_midday == True %}<li>Dimanche midi</li>{% endif %}
				{% if user.profile.meal_sunday_evening == True %}<li>Dimanche soir (à emporter)</li>{% endif %}
			</ul>
		{% else %}
		<li>Inscrit à aucun repas</li>
		{% endif %}
		{% if settings.activities_allocated %}
			{% if my_choices %}
			<li>Inscrit à {{ my_choices|length }} activités&nbsp;:
				<ul>
					{% for choice in my_choices %}
					<li><a href="{% url 'activites' %}#{{ choice.slot.activity.slug }}">{{ choice.slot }}</a>
						{% if choice.slot.on_planning %}
							(le {{ choice.slot.start|date:"l à H:i" }}<!--  en {{ choice.slot.room }} -->)
						{% endif %}
					</li>
					{% endfor %}
				</ul>
			</li>
			{% else %}
			<li>Inscrit à aucune activité</li>
			{% endif %}
		{% else %}
			{% if my_choices %}
			<li>{{ my_choices|length }} activités souhaitées&nbsp;:
				<ol>
					{% for choice in my_choices %}
					<li><a href="{% url 'activites' %}#{{ choice.slot.activity.slug }}">{{ choice.slot }}</a>
						{% if choice.slot.on_planning %}
							(le {{ choice.slot.start|date:"l à H:i" }}<!--  en {{ choice.slot.room }} -->)
						{% endif %}
					</li>
					{% endfor %}
				</ol>
			</li>
			{% else %}
			<li>Aucune activité souhaitée</li>
			{% endif %}

		{% endif %}
	</ul>
{% else %}
	<strong>Vous n'avez pas encore renseigné vos choix d'activités.</strong>

	{% if not settings.inscriptions_open %}
		{% if settings.inscriptions_not_open_yet %}
			<p>Les inscriptions aux activités ne sont pas encores ouvertes. Elles ouvrirons le <strong>{{ settings.inscriptions_start|date:"l d F Y à H:i" }}</strong>.</p>
		{% elif settings.inscriptions_have_closed %}
			<p>Les inscriptions aux activités sont fermées.</p>
		{% else %}
			<p>Les inscriptions aux activités ne sont pas encores ouvertes ou ont été fermées.</p>
		{% endif %}
	{% elif settings.inscriptions_end %}
		<p>les inscriptions aux activités sont ouvertes jusqu'au {{ settings.inscriptions_end|date:"l d F Y à H:i" }}).</p>
	{% endif %}
	<br><br>
{% endif %}

<div class="flex wrap">
	{% if user.profile.is_registered %}
		{% if settings.inscriptions_open %}
		<a class="button" href="{% url 'desinscription' %}">Me désinscrire</a>
		<a class="button" href="{% url 'inscription' %}">Modifier mon inscription</a>
		{% else %}
		<script type="text/javascript">
			function clicked() {
				if (confirm(
					'Les inscriptions étant fermées, vous ne pourrez pas vous réinscrire.\nVoulez vous vraiment vous désinscrire?'
				))
					window.location = "{% url 'desinscription' %}";
			}
		</script>
		<button class="button" onclick="clicked();">Me désinscrire</button>
		{% endif %}
	{% elif settings.inscriptions_open %}
	<a class="button" href="{% url 'inscription' %}">S'inscrire</a>
	{% endif %}

	<a class="button" href="{% url 'accounts:update' %}">Modifier mes informations</a>
	<a class="button" href="{% url 'accounts:logout' %}">Déconnexion</a>
</div>

{% endblock %}