admin_pages/urls.py
from django.urls import path, include

from admin_pages import views

urlpatterns = [
	path('', views.AdminView.as_view(), name="index"),
	path('export/activities/', views.ExportActivities.as_view(), name="activities.csv"),
	path('export/slots/', views.ExportSlots.as_view(), name="slots.csv"),
	path('export/participants/', views.ExportParticipants.as_view(), name="participants.csv"),
	path('export/activity_choices/', views.ExportActivityChoices.as_view(), name="activity_choices.csv"),
	path('email/send_user_emails_0564946523/', views.SendUserEmail.as_view(), name="email_users"),
	path('email/send_orga_emails_5682480453/', views.SendOrgaEmail.as_view(), name="email_orgas"),
	path('email/new_email/', views.NewEmail.as_view(), name="email_new"),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import RedirectView
from django.urls import path, include

from home import views

sitemaps = {"static_pages": views.StaticViewSitemap}

urlpatterns = [
	path('', views.HomeView.as_view(), name = 'home'),
	path('inscription/', views.RegisterView.as_view(), name = 'inscription'),
	path('desinscription/', views.UnregisterView.as_view(), name="desinscription"),
	path('activites/', views.ActivityView.as_view(), name = 'activites'),
	path('activites/nouvelle/', views.ActivitySubmissionView.as_view(), name = 'activity_submission'),
	path('faq/', views.FAQView.as_view(), name = 'FAQ'),
	path("profil/", views.ProfileView.as_view(), name="profile"),
	path('favicon.ico', RedirectView.as_view(url='/static/imgs/favicon.ico')),
	path(
		'sitemap.xml', sitemap, {'sitemaps': sitemaps},
		name='django.contrib.sitemaps.views.sitemap'
	),
	path('admin_pages/', include(('admin_pages.urls', 'admin_pages'), namespace="admin_pages")),
	path('comptes/', include("accounts.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interludes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
        path('admin/', admin.site.urls),
        path('', include('home.urls')),
    ]

admin_pages/models.py
from django.db import models

# Create your models here.

admin_pages/forms.py
from django import forms
from django.conf import settings
from django.db.models import TextChoices

from shared.forms import FormRenderMixin


class Recipients(TextChoices):
	ALL = ("a", "tous les utilisateurs")
	REGISTERED = ("b", "tous les inscrits")

class SendEmailForm(forms.Form):
	"""Formulaire pour un envoie d'email
	à tous les utilisateurs/inscrits"""

	dest = forms.ChoiceField(
		choices=Recipients.choices, required=True,
		label="Envoyer à", initial=Recipients.REGISTERED,
	)
	subject = forms.CharField(
		max_length=100, required=True,
		label="Sujet", initial=settings.USER_EMAIL_SUBJECT_PREFIX,
		strip=True
	)
	text = forms.CharField(
		label="Contenu", strip=True, widget=forms.Textarea
	)

admin_pages/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import mail_admins, send_mass_mail
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, RedirectView, TemplateView

from accounts.models import EmailUser
from home import models
from home.views import get_planning_context
from site_settings.models import Colors, SiteSettings
from shared.views import CSVWriteView, SuperuserRequiredMixin
from interludes import settings as site_settings

from admin_pages.forms import Recipients, SendEmailForm

# ==============================
# Main Admin views
# ==============================


class AdminView(SuperuserRequiredMixin, TemplateView):
	template_name = "admin.html"

	def get_metrics(self):
		registered = models.ParticipantModel.objects.filter(
			is_registered=True, user__is_active=True
		)
		acts = models.ActivityModel.objects.all()
		slots_in = models.SlotModel.objects.all()
		wishes = models.ActivityChoicesModel.objects.filter(
			participant__is_registered=True, participant__user__is_active=True
		)
		class metrics:
			participants = registered.count()
			ulm = registered.filter(school=models.ParticipantModel.ENS.ENS_ULM).count()
			lyon = registered.filter(school=models.ParticipantModel.ENS.ENS_LYON).count()
			rennes = registered.filter(school=models.ParticipantModel.ENS.ENS_RENNES).count()
			saclay = registered.filter(school=models.ParticipantModel.ENS.ENS_CACHAN).count()
			non_registered = EmailUser.objects.filter(is_active=True).count() - participants
			# mugs = registered.filter(mug=True).count()
			sleeps = registered.filter(sleeps=True).count()
			paid = registered.filter(paid=True).count()

			meal1 = registered.filter(meal_friday_evening=True).count()
			meal2 = registered.filter(meal_saturday_morning=True).count()
			meal3 = registered.filter(meal_saturday_midday=True).count()
			meal4 = registered.filter(meal_saturday_evening=True).count()
			meal5 = registered.filter(meal_sunday_morning=True).count()
			meal6 = registered.filter(meal_sunday_midday=True).count()
			meal7 = registered.filter(meal_sunday_evening=True).count()
			meals = meal1 + meal2 + meal3 + meal4 + meal5 + meal6

			activites = acts.count()
			displayed = acts.filter(display=True).count()
			act_ins = acts.filter(display=True, must_subscribe=True).count()
			communicate = acts.filter(communicate_participants=True).count()
			st_present = acts.filter(display=True, status=models.ActivityModel.Status.PRESENT).count()
			st_distant = acts.filter(display=True, status=models.ActivityModel.Status.DISTANT).count()
			st_both = acts.filter(display=True, status=models.ActivityModel.Status.BOTH).count()

			slots = slots_in.count()
			true_ins = slots_in.filter(subscribing_open=True).count()
			wish = wishes.count()
			granted = wishes.filter(accepted=True).count()
			malformed = models.ActivityChoicesModel.objects.filter(slot__subscribing_open=False).count()

		return metrics

	def validate_activity_participant_nb(self):
		""" Vérifie que le nombre de participant inscrit
		à chaque activité est compris entre le min et le max"""
		slots = models.SlotModel.objects.filter(subscribing_open=True)
		min_fails = ""
		max_fails = ""
		for slot in slots:
			total = models.ActivityChoicesModel.objects.filter(
				slot=slot, accepted=True, participant__is_registered=True,
				participant__user__is_active=True
			).aggregate(total=Count("id"))["total"]
			max = slot.activity.max_participants
			min = slot.activity.min_participants
			if max != 0 and max < total:
				max_fails += "<br> &bullet;&ensp;{}: {} inscrits (maximum {})".format(
					slot, total, max
				)
			if min > total:
				min_fails += "<br> &bullet;&ensp;{}: {} inscrits (minimum {})".format(
					slot, total, min
				)
		message = ""
		if min_fails:
			message += '<li class="error">Activités en sous-effectif : {}</li>'.format(min_fails)
		else:
			message += '<li class="success">Aucune activité en sous-effectif</li>'
		if max_fails:
			message += '<li class="error">Activités en sur-effectif : {}</li>'.format(max_fails)
		else:
			message += '<li class="success">Aucune activité en sur-effectif</li>'
		return message

	def validate_activity_conflicts(self):
		"""Vérifie que personne n'est inscrit à des activités simultanées"""
		slots = models.SlotModel.objects.filter(subscribing_open=True)
		conflicts = []
		for i, slot_1 in enumerate(slots):
			for slot_2 in slots[i+1:]:
				if slot_1.conflicts(slot_2):
					conflicts.append((slot_1, slot_2))
		base_qs = models.ActivityChoicesModel.objects.filter(
			accepted=True, participant__is_registered=True,
			participant__user__is_active=True
		)
		errors = ""
		for slot_1, slot_2 in conflicts:
			participants_1 = {x.participant for x in base_qs.filter(slot=slot_1)}
			participants_2 = {x.participant for x in base_qs.filter(slot=slot_2)}
			intersection = participants_1.intersection(participants_2)
			if intersection:
				errors += '<br> &bullet;&ensp; {} participe à la fois à "{}" et à "{}"'.format(
					", ".join(str(x) for x in intersection), slot_1, slot_2
				)

		if errors:
			return '<li class="error">Des participants ont plusieurs activités au même moment :{}</li>'.format(
				errors
			)
		return '<li class="success">Aucun inscrit à plusieurs activités simultanées</li>'

	def validate_slot_less(self):
		"""verifie que toutes les activité demandant une liste de participant ont un créneaux"""
		activities = models.ActivityModel.objects.filter(communicate_participants=True)
		errors = ""
		for activity in activities:
			count = models.SlotModel.objects.filter(activity=activity).count()
			if count == 0:
				errors += "<br> &bullet;&ensp; {}".format(activity.title)
		if errors:
			return '<li class="error">Certaines activités demandant une liste de participants n\'ont pas de créneaux :{}<br>Leurs orgas vont recevoir un mail inutile.</li>'.format(
				errors
			)
		return '<li class="success">Toutes les activités demandant une liste de participants ont au moins un créneau</li>'

	def validate_multiple_similar_inscription(self):
		"""verifie que personne n'est inscrit à la même activité plusieurs fois"""
		slots = models.SlotModel.objects.filter(subscribing_open=True)
		conflicts = []
		for i, slot_1 in enumerate(slots):
			for slot_2 in slots[i+1:]:
				if slot_1.activity == slot_2.activity:
					conflicts.append((slot_1, slot_2))
		base_qs = models.ActivityChoicesModel.objects.filter(
			accepted=True, participant__is_registered=True,
			participant__user__is_active=True
		)
		errors = ""
		for slot_1, slot_2 in conflicts:
			participants_1 = {x.participant for x in base_qs.filter(slot=slot_1)}
			participants_2 = {x.participant for x in base_qs.filter(slot=slot_2)}
			intersection = participants_1.intersection(participants_2)
			if intersection:
				errors += '<br> &bullet;&ensp; {} inscrit aux créneaux "{}" et  "{}" de l\'activité "{}"'.format(
					", ".join(str(x) for x in intersection), slot_1, slot_2, slot_1.activity
				)

		if errors:
			return '<li class="error">Des participants sont inscrits plusieurs fois à la même activité :{}</li>'.format(
				errors
			)
		return '<li class="success">Aucun inscrit plusieurs fois à une même activité</li>'

	def planning_validation(self):
		"""Vérifie que toutes les activités ont le bon nombre de créneaux
		dans le planning"""
		errors = ""
		activities = models.ActivityModel.objects.all()
		for activity in activities:
			nb_wanted = activity.desired_slot_nb
			nb_got = activity.slots.count()
			if nb_wanted != nb_got:
				errors += '<br> &bullet;&ensp; "{}" souhaite {} crénaux mais en a {}.'.format(
					activity.title, nb_wanted, nb_got
				)
		if errors:
			return '<li class="error">Certaines activités ont trop/pas assez de crénaux :{}</li>'.format(
				errors
			)
		return '<li class="success">Toutes les activités ont le bon nombre de crénaux</li>'

	def validate_activity_allocation(self):
		settings = SiteSettings.load()
		validations = '<ul class="messagelist">'

		# validate global settings
		if not settings.inscriptions_open:
			validations += '<li class="success">Les inscriptions sont fermées</li>'
		else:
			validations += '<li class="error">Les inscriptions sont encores ouvertes</li>'
		if settings.activities_allocated:
			validations += '<li class="success">La répartition est marquée comme effectuée</li>'
		else:
			validations += '<li class="error">La répartition n\'est pas marquée comme effectuée</li>'

		# longer validations
		validations += self.validate_activity_participant_nb()
		validations += self.validate_activity_conflicts()
		validations += self.validate_multiple_similar_inscription()
		validations += self.validate_slot_less()

		if settings.discord_link:
			validations += '<li class="success">Le lien du discord est renseigné</li>'
		else:
			validations += '<li class="error">Le lien du discord n\'est pas renseigné</li>'

		validations += '</ul>'

		user_email_nb = models.ParticipantModel.objects.filter(
			is_registered=True, user__is_active=True
		).count()
		orga_email_nb = models.ActivityModel.objects.filter(
			communicate_participants=True
		).count()

		return {
			"validations": validations,
			"user_email_nb": user_email_nb,
			"orga_email_nb": orga_email_nb,
			"validation_errors": '<li class="error">' in validations,
			"planning_validation": self.planning_validation(),
		}

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context["metrics"] = self.get_metrics()
		context.update(get_planning_context())
		context.update(self.validate_activity_allocation())
		return context


# ==============================
# DB Export Views
# ==============================


class ExportActivities(SuperuserRequiredMixin, CSVWriteView):
	filename = "activites_interludes"

admin_pages/templates/admin.html
{% extends "base.html" %}
{% load static %}
{% block nav_admin %}current{% endblock %}

{% block head %}
<script src="{% static 'js/vis-timeline.min.js' %}"></script>
{% endblock %}

{% block "content" %}
	<h2>Page d'administration</h2>
	<p><strong>Version {{ constants.WEBSITE_FULL_VERSION }}</strong></p>
	<div class="flex wrap">
		<a class="button" href="{% url 'admin_pages:participants.csv' %}"><i class="fa fa-download"></i> Participants</a>
		<a class="button" href="{% url 'admin_pages:activities.csv' %}"><i class="fa fa-download"></i> Activités</a>
		<a class="button" href="{% url 'admin_pages:slots.csv' %}"><i class="fa fa-download"></i> Crénaux</a>
		<a class="button" href="{% url 'admin_pages:activity_choices.csv' %}"><i class="fa fa-download"></i> Choix d'activités</a>
	</div>
	<ul class="messagelist">
		<li class="info">
	Pour plus d'options d'accès et de modifications, aller à la <a href="{% url 'admin:index' %}">page d'administration de django</a>.
	<br>N'y modifiez rien si vous n'êtes pas sûrs de ce que cela fait.
		</li></ul>

	<h2>Paramètres du site</h2>

		<ul>
			<li>La création de compte est {% if settings.registrations_open %}ouverte{% else %}fermée{% endif %}.</li>
			<li>Les inscriptions sont {% if settings.inscriptions_open %}ouvertes{% else %}fermées{% endif %}. Dates informatives:
				<ul>
					<li>Ouverture : {{ settings.inscriptions_start|default:"non fixée" }}</li>
					<li>Fermeture : {{ settings.inscriptions_end|default:"non fixée" }}</li>
				</ul>
			</li>
			<li>Les emails des orgas sont {% if settings.show_host_emails %}affichés sur la page activité{% else %}masqués{% endif %}.</li>
			<li>Le planning {% if settings.display_planning %}est affiché{% else %}n'est pas affiché{% endif %}.</li>
			<li>La répartition des activités {% if settings.activities_allocated %}est effectuée et affichée{% else %}n'est pas faite/affichée{% endif %}.</li>
			<li>{% if settings.global_message %}Un message global est affiché{% else %}Aucun message global{% endif %}.</li>
			<li>Le lien du serveur discord {% if settings.discord_link %}est affiché{% else %}n'est pas affiché{% endif %}.</li>
			<li>L'envoi d'email en masse est {% if settings.allow_mass_email %}activé{% else %}désactivé{% endif %}</li>
		</ul>

	<h2>Métriques</h2>

	<div class="flex wrap lines">
		<div class="stat">
			<div class="qty">Participants</div>
			<div class="nb_big">{{ metrics.participants }}</div>
		</div>
		<div class="stat">
			<div class="qty">Ulm</div>
			<div class="nb_small">{{ metrics.ulm }}</div>
		</div>
		<div class="stat">
			<div class="qty">Lyon</div>
			<div class="nb_small">{{ metrics.lyon }}</div>
		</div>
		<div class="stat">
			<div class="qty">Rennes</div>
			<div class="nb_small">{{ metrics.rennes }}</div>
		</div>
		<div class="stat">
			<div class="qty">Paris-Saclay</div>
			<div class="nb_small">{{ metrics.saclay }}</div>
		</div>
		<div class="stat">
			<div class="qty">Non inscrits</div>
			<div class="nb_small">{{ metrics.non_registered }}</div>
		</div>
		<div class="stat">
			<div class="qty">Dormeurs</div>
			<div class="nb_small">{{ metrics.sleeps }}</div>
		</div>
		<div class="stat">
			<div class="qty">Payé⋅es</div>
			<div class="nb_small">{{ metrics.paid }}</div>
		</div>
	</div>

	<div class="flex wrap lines">
		<div class="stat">
			<div class="qty">Repas</div>
			<div class="nb_big">{{ metrics.meals }}</div>
		</div>
		<div class="stat">
			<div class="qty">Vendredi</div>
			<div class="nb_small">{{ metrics.meal1 }}</div>
		</div>
		<div class="stat">
			<div class="qty">S matin</div>
			<div class="nb_small">{{ metrics.meal2 }}</div>
		</div>
		<div class="stat">
			<div class="qty">S midi</div>
			<div class="nb_small">{{ metrics.meal3 }}</div>
		</div>
		<div class="stat">
			<div class="qty">S soir</div>
			<div class="nb_small">{{ metrics.meal4 }}</div>
		</div>
		<div class="stat">
			<div class="qty">D matin</div>
			<div class="nb_small">{{ metrics.meal5 }}</div>
		</div>
		<div class="stat">
			<div class="qty">D midi</div>
			<div class="nb_small">{{ metrics.meal6 }}</div>
		</div>
		<div class="stat">
			<div class="qty">D soir</div>
			<div class="nb_small">{{ metrics.meal7 }}</div>
		</div>
	</div>

	<div class="flex wrap lines">
		<div class="stat">
			<div class="qty">Activités</div>
			<div class="nb_big">{{ metrics.activites }}</div>
		</div>
		<div class="stat">
			<div class="qty">Affichées</div>
			<div class="nb_small">{{ metrics.displayed }}</div>
		</div>
		<div class="stat">
			<div class="qty">Inscription*</div>
			<div class="nb_small">{{ metrics.act_ins }}</div>
		</div>
		<div class="stat">
			<div class="qty">Mail orga</div>
			<div class="nb_small">{{ metrics.communicate }}</div>
		</div>
		<div class="stat">
			<div class="qty">Présentiel</div>
			<div class="nb_small">{{ metrics.st_present }}</div>
		</div>
		<div class="stat">
			<div class="qty">Distanciel</div>
			<div class="nb_small">{{ metrics.st_distant }}</div>
		</div>
		<div class="stat">
			<div class="qty">Les deux</div>
			<div class="nb_small">{{ metrics.st_both }}</div>
		</div>
	</div>

	<div class="flex wrap lines">
		<div class="stat">
			<div class="qty">Planning</div>
			<div class="nb_big">{{ metrics.slots }}</div>
		</div>
		<div class="stat">
			<div class="qty">Inscription*</div>
			<div class="nb_small">{{ metrics.true_ins }}</div>
		</div>
		<div class="stat">
			<div class="qty">Souhaits</div>
			<div class="nb_small">{{ metrics.wish }}</div>
		</div>
		<div class="stat">
			<div class="qty">Obtenus</div>
			<div class="nb_small">{{ metrics.granted }}</div>
		</div>
		<div class="stat">
			<div class="qty">Malformé</div>
			<div class="nb_small">{{ metrics.malformed }}</div>
		</div>
	</div>

	<p>*Une activité peut avoir plusieurs créneaux sur le planning. Les inscriptions se font par créneaux donc le nombre
		d'inscriptions de la catégorie "Activités" est seulement informatif .
	</p>

	{% if metrics.malformed %}
	<ul class="messagelist"><li class="error">
		Des activités non ouvertes aux inscriptions apparaissent dans les listes de souhait.
	</li></ul>
	{% endif %}

	<h2>Prévisualisation du planning</h2>

	<ul class="messagelist">
		{{ planning_validation|safe }}
	</ul>

	<p>Vous pouver uploader une version PDF dans le réglages (depuis django-admin)</p>

	{% include "_planning.html" %}

	<h2>Répartition des activités</h2>

	<p>La répartition se fait depuis la <a href="{% url 'admin:index' %}">page d'administration de django</a>,
	dans la rebrique "Choix d'activités" via la colonne "obtenue".</p>

	<p>Une fois la répartition effectuée, vérifiez qu'elle passe les tests avant d'envoyer les mails</p>

	{{ validations|safe }}

	<script type="text/javascript">
		{% if validation_errors %}
		  const errors = "!! Cette répartition ne passe PAS tous les tests !!\n\n";
		{% else %}
			const errors = "";
		{% endif %}
		{% if not settings.user_notified and settings.allow_mass_mail %}
			function mail_inscrits() {
				if (confirm(
					`${errors}Cette action va envoyer {{ user_email_nb }} emails.\nÊtes-vous sur de vouloir continuer ?`
				))
					window.location = "{% url 'admin_pages:email_users' %}";
			}
		{% endif %}
		{% if not settings.orga_notified and settings.allow_mass_mail %}
			function mail_orgas() {
				if (confirm(
					`${errors}Cette action va envoyer {{ orga_email_nb }} emails.\nÊtes-vous sur de vouloir continuer ?`
				))
					window.location = "{% url 'admin_pages:email_orgas' %}";
			}
		{% endif %}
	</script>
	<p class="centered"><i class="fas fa-exclamation-triangle"></i> N'ENVOYER LES EMAILS QUE SI VOUS ÊTES SUR DE VOUS ! <i class="fas fa-exclamation-triangle"></i></p>
	{% if not settings.allow_mass_mail %}
		<p>L'envoi d'emails collectifs est désactivé dans les réglages. Activez le avant d'envoyer
			et redésactivez le après.
		</p>
	{% endif %}
	{% if settings.user_notified %}
		<p>Un email communiquant la répartition aux utilisateurs a déjà été envoyé.
			(Modifiez les paramètres s'il faut en renvoyer un)
		</p>
	{% else %}
		<p>L'email aux inscrits enverra un email à tous les utilisateurs inscrits.
			Il communiquera également le lien du discord si celui-ci est renseigné.</p>
	{% endif %}
	{% if settings.orga_notified %}
		<p>Un email communiquant les inscrits aux organisateur à déjà été envoyé.
			(Modifiez les paramètres s'il faut en renvoyer un)
		</p>
		{% else %}
		<p>L'email aux orgas enverra un email uniquement aux orgas des activités qui ont demandé de communiquer la liste de participants.</p>
	{% endif %}

	<div class="flex wrap">
		{% if settings.user_notified or not settings.allow_mass_mail %}
			<button class="button disabled">Email aux inscrits</button>
		{% else %}
			<button class="button" onclick="mail_inscrits();">Email aux inscrits</button>
		{% endif %}
		{% if settings.orga_notified or not settings.allow_mass_mail %}
			<button class="button disabled">Email aux orgas</button>
		{% else %}
			<button class="button" onclick="mail_orgas();">Email aux orgas</button>
		{% endif %}
	</div>

	<h2>Mail aux utilisateurs</h2>

	<p>Écrire un mail aux utilisateurs (tous ou seulement les inscrits)</p>

	<p>Évitez de spammer. N'envoyez que si vraiment nécessaire.</p>

	<p><a class="button{% if not settings.allow_mass_mail %} disabled{% endif %}" href="{% url 'admin_pages:email_new' %}">Écrire un nouveau mail</a></p>
{% endblock %}

admin_pages/templates/send_email.html
{% extends "base.html" %}
{% load static %}

{% block "content" %}
<h2>Envoyer un email</h2>

<p>
	Ce formulaire permet d'envoyer un mail à tous les comptes du site
	(ou seulement aux comptes actuellements inscrits).
	À utiliser avec modération.
</p>
<ul>
	<li>Nombre de comptes : {{ accounts_nb }}</li>
	<li>Nombre d'inscrits : {{ registered_nb }}</li>
</ul>

<form method="post" action="{% url 'admin_pages:email_new' %}">
	{% csrf_token %}
	<table>
		<tr><td><strong>De :</strong></td><td>{{ from_email }}</td></tr>
		<tr><td><strong>Envoyer à : <strong></td><td>{{ form.dest }}</td></tr>
		<tr><td><strong>Sujet : <strong></td><td>{{ form.subject }}</td></tr>
	</table>
	{{ form.text }}
	<br>
	<div class="flex">
		<input type="submit" value="Envoyer">
		<a class="button" href="{% url 'admin_pages:index' %}">Annuler</a>
	</div>
</form>
{% endblock %}