accounts/urls.py
from django.urls import include, path

from accounts import views

app_name = "accounts"

urlpatterns = [
	path("login/", views.LoginView.as_view(), name="login"),
	path("logout/", views.LogoutView.as_view(), name="logout"),
	path("create/", views.CreateAccountView.as_view(), name="create"),
	path("update/", views.UpdateAccountView.as_view(), name="update"),
	path("change_password/", views.UpdatePasswordView.as_view(), name="change_password"),
	path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),
	path("password_reset/", views.ResetPasswordView.as_view(), name="password_reset"),
	path(
		"password_reset/<uidb64>/<token>/",
		views.ResetPasswordConfirmView.as_view(),
		name="password_reset_confirm"
	),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import RedirectView
from django.urls import path, include

from home import views

sitemaps = {"static_pages": views.StaticViewSitemap}

urlpatterns = [
	path('', views.HomeView.as_view(), name = 'home'),
	path('inscription/', views.RegisterView.as_view(), name = 'inscription'),
	path('desinscription/', views.UnregisterView.as_view(), name="desinscription"),
	path('activites/', views.ActivityView.as_view(), name = 'activites'),
	path('activites/nouvelle/', views.ActivitySubmissionView.as_view(), name = 'activity_submission'),
	path('faq/', views.FAQView.as_view(), name = 'FAQ'),
	path("profil/", views.ProfileView.as_view(), name="profile"),
	path('favicon.ico', RedirectView.as_view(url='/static/imgs/favicon.ico')),
	path(
		'sitemap.xml', sitemap, {'sitemaps': sitemaps},
		name='django.contrib.sitemaps.views.sitemap'
	),
	path('admin_pages/', include(('admin_pages.urls', 'admin_pages'), namespace="admin_pages")),
	path('comptes/', include("accounts.urls")),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interludes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
        path('admin/', admin.site.urls),
        path('', include('home.urls')),
    ]

home/forms.py
from django import forms
from django.core.exceptions import ValidationError

from home import models
from shared.forms import FormRenderMixin


class InscriptionForm(FormRenderMixin, forms.ModelForm):

	class Meta:
		model = models.ParticipantModel
		fields = (
			"school", "sleeps", # "mug",
			"meal_friday_evening", "meal_saturday_morning", "meal_saturday_midday",
			"meal_saturday_evening", "meal_sunday_morning", "meal_sunday_midday", "meal_sunday_evening",
			"paid","nb_murder", "comment"
		)

	field_groups = [["school"], ["sleeps"], #["mug"],
		[
			"meal_friday_evening", "meal_saturday_morning", "meal_saturday_midday",
			"meal_saturday_evening", "meal_sunday_morning", "meal_sunday_midday", "meal_sunday_evening"
		],
		["paid"],["nb_murder"], ["comment"]
	]

	def save(self, *args, commit=True, **kwargs):
		participant = super().save(*args, commit=False, **kwargs)
		participant.is_registered = True
		if commit:
			participant.save()
		return participant

class ActivityForm(FormRenderMixin, forms.ModelForm):
	class Meta:
		model = models.ActivityChoicesModel
		fields = ("slot",)
		labels = {"slot":""}

	def __init__(self, *args, **kwargs):
		super(ActivityForm, self).__init__(*args, **kwargs)
		slots = models.SlotModel.objects.filter(subscribing_open=True)
		self.fields['slot'].queryset = slots

class BaseActivityFormSet(forms.BaseFormSet):
	"""Form set that fails if duplicate activities"""
	def clean(self):
		"""Checks for duplicate activities"""
		if any(self.errors):
			# Don't bother validating the formset unless each form is valid on its own
			return
		activities = []
		for form in self.forms:
			if self.can_delete and self._should_delete_form(form):
				continue
			activity = form.cleaned_data.get('slot')
			if activity is None:
				continue
			if activity in activities:
				raise ValidationError("Vous ne pouvez pas sélectionner une même activtté plusieurs fois")
			activities.append(activity)


class ActivitySubmissionForm(FormRenderMixin, forms.ModelForm):

	class Meta:
		model = models.ActivityModel
		fields = (
			"title", "act_type", "game_type", "description",

			"host_name", "host_email", "host_info",

			"must_subscribe", "communicate_participants",
			"max_participants",	"min_participants",

			"duration", "desired_slot_nb",
			"available_friday_evening",
			"available_friday_night",
			"available_saturday_morning",
			"available_saturday_afternoon",
			"available_saturday_evening",
			"available_saturday_night",
			"available_sunday_morning",
			"available_sunday_afternoon",
			"constraints",

			#"status",
			"needs",

			"comments",
		)

	def clean(self):
		cleaned_data = super().clean()
		maxi = cleaned_data.get("max_participants")
		mini = cleaned_data.get("min_participants")
		if maxi != 0 and mini > maxi:
			raise forms.ValidationError(
				"Le nombre minimal de participants est supérieur au nombre maximal",
				code="invalid_order"
			)
		return cleaned_data

	def save(self, *args, commit=True, **kwargs):
		"""Enregistre l'activité dans la base de données"""
		activity = models.ActivityModel(
			**self.cleaned_data,
		)
		if commit:
			activity.save()
		return activity

home/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sitemaps import Sitemap
from django.forms import formset_factory
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, RedirectView, TemplateView, View

from home import models
from home.forms import ActivityForm, ActivitySubmissionForm, BaseActivityFormSet, InscriptionForm
from site_settings.models import SiteSettings


# ==============================
# Site static pages
# ==============================


class HomeView(TemplateView):
	"""Vue pour la page d'acceuil"""
	template_name = "home.html"

def get_planning_context():
	"""Returns the context dict needed to display the planning"""
	settings = SiteSettings.load()
	context = dict()
	context['planning'] = models.SlotModel.objects.filter(on_planning=True).order_by("title")
	if settings.date_start is not None:
		context['friday'] = settings.date_start.day
		context['saturday'] = (settings.date_start + timedelta(days=1)).day
		context['sunday'] = (settings.date_start + timedelta(days=2)).day
	else:
		context['friday'] = 1
		context['saturday'] = 2
		context['sunday'] = 3
	return context

class ActivityView(TemplateView):
	"""Vue pour la liste des activités"""
	template_name = "activites.html"

	def get_context_data(self, **kwargs):
		"""ajoute la liste des activités au contexte"""
		context = super(ActivityView, self).get_context_data(**kwargs)
		context['activities'] = models.ActivityModel.objects.filter(display=True).order_by("title")
		context.update(get_planning_context())
		return context


class FAQView(TemplateView):
	"""Vue pour la FAQ"""
	template_name = "faq.html"


# ==============================
# Profile and registration
# ==============================


class ProfileView(LoginRequiredMixin, TemplateView):
	"""Vue des actions de gestion de son profil"""
	template_name = "profile.html"
	redirect_field_name = "next"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		settings = SiteSettings.load()
		if settings.activities_allocated:
			my_choices = models.ActivityChoicesModel.objects.filter(
				participant=self.request.user.profile,
				accepted=True
			)
		else:
			my_choices = models.ActivityChoicesModel.objects.filter(
				participant=self.request.user.profile
			)

		context["my_choices"] = my_choices
		return context


class RegisterClosed(TemplateView):
	"""Vue pour quand les inscriptions ne sont pas ouvertes"""
	template_name = "inscription/closed.html"

class RegisterSignIn(TemplateView):
	"""Vue affichée quand les inscriptions sont ouverte mais
	l'utilisateur n'est pas connecté"""
	template_name = "inscription/signin.html"

class RegisterUpdateView(LoginRequiredMixin, TemplateView):
	"""Vue pour s'inscrire et modifier son inscription"""
	template_name = "inscription/form.html"
	form_class = InscriptionForm
	formset_class = formset_factory(form=ActivityForm, extra=3, formset=BaseActivityFormSet)
	success_url = reverse_lazy("profile")

	@staticmethod
	def get_slots(participant):
		activities = models.ActivityChoicesModel.objects.filter(participant=participant).order_by("priority")
		return [{"slot": act.slot} for act in activities]

	@staticmethod
	def set_activities(participant, formset):
		# delete old activites
		models.ActivityChoicesModel.objects.filter(participant=participant).delete()

		priority = 0
		for form in formset:
			data = form.cleaned_data
			if data:
				slot = data["slot"]
				models.ActivityChoicesModel(
					priority=priority, participant=participant, slot=slot
				).save()
				priority += 1

	def get(self, request, *args, **kwargs):
		participant = request.user.profile
		slots = self.get_slots(participant)
		form = self.form_class(instance=participant)
		formset = self.formset_class(initial=slots)
		context = {"form": form, "formset": formset}
		return render(request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		settings = SiteSettings.load()
		form = self.form_class(request.POST, instance=request.user.profile)
		if settings.activity_inscriptions_open : # meal + sleep + activities open
			formset = self.formset_class(request.POST)
			if not (form.is_valid() and formset.is_valid()):
				context = {"form": form, "formset": formset}
				return render(request, self.template_name, context)
			self.set_activities(request.user.profile, formset)

		else: # only meal and sleep open
			if not form.is_valid():
				participant = request.user.profile
				slots = self.get_slots(participant)
				formset = self.formset_class(initial=slots)
				context = {"form": form, "formset": formset}
				return render(request, self.template_name, context)
		
		form.save()

		messages.success(request, "Votre inscription a bien été enregistrée")
		return redirect(self.success_url, permanent=False)

class RegisterView(View):
	"""Vue pour l'inscription
	repartie sur les vue RegisterClosed, RegisterSignIn et RegisterUpdateView"""
	def dispatch(self, request, *args, **kwargs):
		settings = SiteSettings.load()
		if not settings.inscriptions_open:
			return RegisterClosed.as_view()(request)
		if not request.user.is_authenticated:
			return RegisterSignIn.as_view()(request)
		return RegisterUpdateView.as_view()(request)


class UnregisterView(LoginRequiredMixin, RedirectView):
	pattern_name = "profile"

	def get_redirect_url(self, *args, **kwargs):
		participant = self.request.user.profile
		participant.is_registered = False
		participant.save()
		messages.success(self.request, "Vous avez été désinscrit")
		return reverse(self.pattern_name)


# ==============================
# Activity Submission Form
# ==============================


class ActivitySubmissionView(LoginRequiredMixin, FormView):
	"""Vue pour proposer une activité"""
	template_name = "activity_submission.html"
	form_class = ActivitySubmissionForm
	success_url = reverse_lazy("profile")

	@staticmethod
	def submission_check():
		"""Vérifie si le formulaire est ouvert ou non"""
		settings = SiteSettings.load()
		return settings.activity_submission_open

	def get_initial(self):
		init = super().get_initial()
		user = self.request.user
		init.update({
			"host_name": "{} {}".format(user.first_name, user.last_name),
			"host_email": user.email,
		})
		return init

	def not_open(self, request):
		"""Appelé quand le formulaire est désactivé"""
		messages.error(request, "La soumission d'activité est desactivée")
		return redirect(self.success_url, permanent=False)

	def get(self, request, *args, **kwargs):
		if not self.submission_check():
			return self.not_open(request)
		return super().get(self, request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		if not self.submission_check():
			return self.not_open(request)
		form = self.form_class(request.POST)
		if not form.is_valid():
			context = self.get_context_data()
			context["form"] = form
			return render(request, self.template_name, context)

		form.save()

		messages.success(request, "Votre activité a bien été enregistrée. Elle sera affichée sur le site après relecture par les admins.")
		return redirect(self.success_url, permanent=False)


# ==============================
# Sitemap
# ==============================


class StaticViewSitemap(Sitemap):
	"""Vue générant la sitemap.xml du site"""
	changefreq = 'monthly'

	def items(self):
		"""list of pages to appear in sitemap"""
		return ["home", "inscription", "activites", "FAQ"]

	def location(self, item):
		"""real url of an item"""
		return reverse(item)

	def priority(self, obj):
		"""priority to appear in sitemap"""
		# Priorize home page over the rest in search results
		if obj == "home" or obj == "":
				return 0.8
		else:
			return None # defaults to 0.5 when unset

home/templates/inscription/closed.html
{% extends "base.html" %}

{% block nav_inscription %}current{% endblock %}

{% block "content" %}
	<h2>Inscriptions à l'événement</h2>
	<p> L'inscription est fermée </p>

	<h2>Inscriptions aux activités</h2>
	{% if settings.inscriptions_not_open_yet %}
		<p>Les inscriptions aux activités ne sont pas encores ouvertes.</p>
		<p>Leur ouverture est prévue le <strong>{{ settings.inscriptions_start|date:"l d F Y à H:i" }}</strong>.</p>
		<p>Nous communiquerons par mail via les BDE des différentes écoles pour leur ouverture.</p>
	{% elif settings.inscriptions_have_closed %}
		<p>Les inscriptions aux activités sont fermées.</p>
		<p>
			Les inscriptions cette année sont facultatives,
			tu peux quand même rejoindre le {% if settings.discord_link %}<a href="{{ settings.discord_link }}">serveur discord</a>{% else %}serveur discord{% endif %} et participer aux jeux libres et
			aux activités qui ne nécessitent pas d'inscription.
		</p>
		{% if settings.contact_email %}
			<p>Pour tout problème, contacter&nbsp;:<br><span class="antispam">{{ settings.contact_email_reversed }}</span></p>
		{% endif %}
	{% else %}
		<p>Les inscriptions aux activités ne sont pas encores ouvertes ou ont été fermées.</p>
		<p>Nous communiquerons par mail via les BDE des différentes écoles pour leur ouverture.</p>
	{% endif %}
{% endblock %}

home/templates/inscription/form-distanciel.html
{% extends "base.html" %}
{% load static %}

{% block nav_inscription %}current{% endblock %}

{% block "content" %}
	<h2>Inscriptions</h2>

	{% if settings.discord_link %}
	<ul class="messagelist">
		<li class="info">Rejoignez aussi <a href="{{ settings.discord_link }}">le serveur discord</a>,
		C'est là que s'organiseront la plupart des activités.</li>
	</ul>
	{% endif %}

	<form id="main_form" method="post" action="{% url 'inscription' %}">
		{% csrf_token %}

		Cette année, l'événement étant en distanciel, il est gratuit.

		<p>{{ form.school.label_tag }} {{ form.school }}</p>

		<h3>Choix d'activités</h3>

		<p>Saissisez les activités auquelles vous voulez vous inscrire, par ordre de préférence.
			Vous trouverez une description des activités sur <a href="{% url 'activites' %}">cette page</a>.
		</p>
		<p>
			Vous pouvez revenir modifier votre choix jusqu'à la fermeture des
			inscriptions{% if settings.inscriptions_end %} (le {{ settings.inscriptions_end|date:"l d F Y à H:i" }}){% endif %}.
		</p>
		<p>Si vous vous inscrivez à une activité qui nécessite préparation, nous communiquerons
			votre email aux orgas pour qu'iels puissent vous contacter.
		</p>


		{% if formset.non_form_errors %}
		{{ formset.non_form_errors }}
		{% endif %}

		{{ formset.management_data }}
		{{ formset.management_form }}
		{% for form in formset %}
		<div class="activity-form flex">
			{{ form.as_p }}
			<button class="button delete-activity" style="align-self: center; flex-grow: 0;">Supprimer</button>
		</div>
		{% endfor %}
		<button class="button" id="add-activity">Ajouter une activité</button>
		<div class="flex">
			<input type="submit" value="Valider">

			<a class="button" href="{% url 'profile' %}">Annuler</a>
		</div>
	</form>

	<script>
const button_add_activity = document.querySelector("#add-activity");
const button_submit_form = document.querySelector('[type="submit"]');
const activity_form = document.getElementsByClassName("activity-form");
const main_form = document.querySelector("#main_form");
const total_forms = document.querySelector("#id_form-TOTAL_FORMS");

const form_regex = /form-(\d*)-/g;

var form_count = activity_form.length - 1;

function add_new_form(event) {
	// adds a new activity form when clicking on the + button
	event.preventDefault();
	// clone the first form and replaces it's id
	const new_form = activity_form[0].cloneNode(true);
	form_count++;
	new_form.innerHTML = new_form.innerHTML.replace(form_regex, `form-${form_count}-`);
	// add it and increment form total
	main_form.insertBefore(new_form, button_add_activity);
	new_form.querySelector("select").value = "";
	total_forms.setAttribute("value", `${form_count+1}`);
}

button_add_activity.addEventListener("click", add_new_form);

function delete_form(event) {
	if (!event.target.classList.contains("delete-activity")) return;
	event.preventDefault();
	if (form_count == 0) {
		// don't delete the first element
		activity_form[0].querySelector("select").value = "";
		return;
	}
	event.target.parentElement.remove();
	form_count--;
	total_forms.setAttribute("value", `${form_count+1}`);
	// update form numbers
	let count = 0;
	for (const form of activity_form) {
		// the replace changes the field value
		// so we save and restore it
		const select = form.querySelector("select");
		const value = select.value;
		form.innerHTML = form.innerHTML.replace(form_regex, `form-${count++}-`);
		form.querySelector("select").value = value;
	}
}

main_form.addEventListener("click", delete_form);
	</script>
{% endblock %}

home/templates/inscription/form.html
{% extends "base.html" %}
{% load static %}

{% block nav_inscription %}current{% endblock %}

{% block "content" %}
	<form id="main_form" method="post" action="{% url 'inscription' %}">
	{% csrf_token %}

	<h2>Inscription à l'événement</h2>
        <p>L'inscription à l'événement,à l'hébergement
        et aux repas se fait sur cette page.</p>
	
		<h3>École</h3>
		<p>{{ form.school.label_tag }} {{ form.school }}</p>

		<h3>Repas</h3>
		<p>Vous pouvez vous inscrire aux repas ci-dessous :</p>
		<ul>
		    <li>Vendredi soir {{ form.meal_friday_evening }}</li>
		    <li>Petit dej' du samedi {{ form.meal_saturday_morning }}</li>
		    <li>Samedi midi {{ form.meal_saturday_midday }}</li>
		    <li>Samedi soir {{ form.meal_saturday_evening }}</li>
		    <li>Dimanche matin {{ form.meal_sunday_morning }}</li>
		    <li>Dimanche midi {{ form.meal_sunday_midday }}</li>
		    <li>Dimanche soir (à emporter) {{ form.meal_sunday_evening }}</li>
		</ul>
		<p>Les menus sont disponibles sur la <a href="{% url 'home' %}">page d'accueil</a>
		
	    <h3>Hébergement</h3>
	    <p>Pour l'hébergement, nous proposons le logement chez les Saclaysien⋅nes (comme aux InterQ). Si vous souhaitez un hébergement, cochez la case suivante : {{ form.sleeps }} </p>
	    <p>L'idée est de proposer aux normalien⋅nes de Saclay de loger celleux des autres écoles. Si vous avez besoin d'un hébergement vous pouvez compléter <a href="https://framaforms.org/logement-interludes-2023-extes-1668450149">ce questionnaire</a>. Si vous voulez loger quelqu'un <a href="https://framaforms.org/logement-interludes-2023-cote-hebergement-1668438253">c'est ici</a>. Merci à ceux qui veulent bien accueillir !</p>

            <h3>Tarif</h3>
            <p>Le tarif est différent selon si vous percevez un salaire ou non. Êtes-vous payé⋅e : {{ form.paid }}</p>

	<h2>Inscription aux activités</h2>
		
		{% if formset.non_form_errors %}
		{{ formset.non_form_errors }}
		{% endif %}

		{{ formset.management_data }}
		{{ formset.management_form }}
	
	    {% if settings.activity_inscriptions_open %}
	    
	    <p>Vous pouvez vous inscrire à certaines activités sur cette page. La 
	    plupart des activités ne demandent pas d'inscription et seront en libre 
	    accès durant tout l'événement, mais certaines demandent une inscription 
	    à l'avance.</p>

		<h3>Choix d'activités</h3>
		<p>Saissisez les activités auquelles vous voulez vous inscrire, <strong>par ordre de préférence</strong>.
			Vous trouverez une description des activités sur <a href="{% url 'activites' %}">cette page</a>.</p>
			
		<p>Si vous vous inscrivez à une activité qui nécessite préparation, nous communiquerons
			votre email aux orgas pour qu'iels puissent vous contacter.</p>

		{% for form in formset %}
		<div class="activity-form flex">
			{{ form.as_p }}
			<button class="button delete-activity" style="align-self: center; flex-grow: 0;">Supprimer</button>
		</div>
		{% endfor %}
		<button class="button" id="add-activity">Ajouter une activité</button>
		
	{% else %}
	
	    <p>Vous pourrez vous inscrire à certaines activités sur cette page. La 
	    plupart des activités ne demandent pas d'inscription et seront en libre 
	    accès durant tout l'événement, mais certaines demandent une inscription 
	    à l'avance.{% if settings.inscriptions_end %} Les inscriptions aux activités ouvrent le  {{ settings.inscriptions_start|date:"l d F Y à H:i" }}){% endif %}. </p>
	
	{% endif %}
	
		<h3>Expérience</h3>
		<p>Pour vous attribuer au mieux les activités, nous aimerions connaître votre exprérieurnce en murder (jeux de rôles grandeurs nature). Si vous avez perdu le compte, 42 conviendra très bien ;) </p>
		Nombre de murder déjà jouées : {{ form.nb_murder }}
		
	<h2>Commentaire</h2>
		<p>Pour préciser toutes les informations qui vous semblent utiles comme les allergies alimentaires.</p>
		{{ form.comment }}
	
		<p>
			Vous pouvez revenir modifier vos choix jusqu'à la fermeture des
			inscriptions{% if settings.inscriptions_end %} (le {{ settings.inscriptions_end|date:"l d F Y à H:i" }}){% endif %}.
		</p>

		<div class="flex">
			<input type="submit" value="Valider">

			<a class="button" href="{% url 'profile' %}">Annuler</a>
		</div>
	</form>

	<script>
const button_add_activity = document.querySelector("#add-activity");
const button_submit_form = document.querySelector('[type="submit"]');
const activity_form = document.getElementsByClassName("activity-form");
const main_form = document.querySelector("#main_form");
const total_forms = document.querySelector("#id_form-TOTAL_FORMS");

const form_regex = /form-(\d*)-/g;

var form_count = activity_form.length - 1;

function add_new_form(event) {
	// adds a new activity form when clicking on the + button
	event.preventDefault();
	// clone the first form and replaces it's id
	const new_form = activity_form[0].cloneNode(true);
	form_count++;
	new_form.innerHTML = new_form.innerHTML.replace(form_regex, `form-${form_count}-`);
	// add it and increment form total
	main_form.insertBefore(new_form, button_add_activity);
	new_form.querySelector("select").value = "";
	total_forms.setAttribute("value", `${form_count+1}`);
}

button_add_activity.addEventListener("click", add_new_form);

function delete_form(event) {
	if (!event.target.classList.contains("delete-activity")) return;
	event.preventDefault();
	if (form_count == 0) {
		// don't delete the first element
		activity_form[0].querySelector("select").value = "";
		return;
	}
	event.target.parentElement.remove();
	form_count--;
	total_forms.setAttribute("value", `${form_count+1}`);
	// update form numbers
	let count = 0;
	for (const form of activity_form) {
		// the replace changes the field value
		// so we save and restore it
		const select = form.querySelector("select");
		const value = select.value;
		form.innerHTML = form.innerHTML.replace(form_regex, `form-${count++}-`);
		form.querySelector("select").value = value;
	}
}

main_form.addEventListener("click", delete_form);
	</script>
{% endblock %}

home/templates/inscription/signin.html
{% extends "base.html" %}

{% block nav_inscription %}current{% endblock %}

{% block "content" %}
	<h2>Inscriptions</h2>
	<p>Vous devez être connecté pour pouvoir vous inscrire</p>
	<p>Aller à la page de <a href="{% url 'accounts:login' %}">connexion</a> pour vous connecter
	ou à celle de <a href="{% url 'accounts:create' %}">création de compte</a> si vous n'avez pas de compte.</p>
	{% if settings.inscriptions_end %}
		<p>Les inscriptions seront ouvertes jusqu'au {{ settings.inscriptions_end|date:"l d F Y à H:i" }})</p>
	{% endif %}
{% endblock %}